version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_configuracao
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./projeto-configuracao-back-end
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/projeto_configuracao
    depends_on:
      - db

  frontend:
    build: ./projeto-configuracao-front-end
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
