version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_homolog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_configuracao_homolog
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_homolog:/var/lib/mysql

  backend:
    build: ./projeto-configuracao-back-end
    container_name: backend_homolog
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/projeto_configuracao_homolog
    depends_on:
      - db

  frontend:
    build: ./projeto-configuracao-front-end
    container_name: frontend_homolog
    ports:
      - "8080:5173"
    depends_on:
      - backend

volumes:
  mysql_data_homolog: