version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_producao
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_configuracao
    ports:
      - "3310:3306" # ALTERADO: Porta 3310 externa → 3306 interna
    volumes:
      - mysql_data_producao:/var/lib/mysql

  backend:
    build: ./projeto-configuracao-back-end
    container_name: backend_producao
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/projeto_configuracao
    depends_on:
      - db

  frontend:
    build: ./projeto-configuracao-front-end
    container_name: frontend_producao
    ports:
      - "5174:5173"
    depends_on:
      - backend

volumes:
  mysql_data_producao: